version: "3.3"

services:
  frontend:
    build: ./frontend  # Path to your Angular project directory
    image: task-manager-frontend
    ports:
      - "4200:4200"  # Expose Angular's dev server port
    depends_on:
      - backend

  backend:
    build: ./backend  # Path to your Next.js project directory
    image: task-manager-backend
    ports:
      - "3001:3001"  # Expose Next.js server port
    environment:
      - MONGODB_URI=mongodb://db:27017/task-manager  # Connect to MongoDB
    depends_on:
      - db

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
